GET http://localhost:3000/users

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "andy",
    "password": "0000"
}

###
POST http://localhost:3000/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZHkiLCJpYXQiOjE2NDEwMzAxOTZ9.ZjFDoNID9Eq8HhIrN8OmxfknsmNIfPqbmm1YenUW6gE"
}

### 
GET http://localhost:3000/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZHkiLCJpYXQiOjE2NDEwMzAxOTYsImV4cCI6MTY0MTAzMDI1Nn0.eezleBEq-5px6YAHThauBC-sjtzMd8Xbna0OR7fWJyQ